# Generated by Django 3.2.4 on 2023-04-06 02:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gestionUsuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento', models.CharField(max_length=200, unique=True, verbose_name='Documento de identidad')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(default='usuario.png', upload_to='')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No declarado')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Union Libre')], max_length=1)),
                ('ocupacion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('es_colaborador', 'Es colaborador'), ('es_instructor', 'Es Instructor')),
            },
            managers=[
                ('objects', gestionUsuarios.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(default=datetime.time(10, 10))),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('instructions', models.TextField()),
                ('total_marks', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=100)),
                ('section', models.CharField(default='Third Year', max_length=100)),
                ('class_code', models.CharField(default='0000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Tiempo_inicial', models.DateTimeField()),
                ('Tiempo_final', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('clase_cumplida', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_instructor', models.CharField(max_length=50, unique=True)),
                ('nombre_instructor', models.CharField(max_length=200)),
                ('apellido_instructor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.classrooms')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.classrooms')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('submitted_time', models.TimeField(auto_now_add=True)),
                ('submitted_on_time', models.BooleanField(default=True)),
                ('marks_alloted', models.IntegerField(default=0)),
                ('submission_file', models.FileField(upload_to='documents')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.assignments')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.students')),
            ],
        ),
        migrations.CreateModel(
            name='instructor_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_instructor', models.DateTimeField(auto_now_add=True)),
                ('especialidad_instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_instructor', models.IntegerField(blank=True, null=True)),
                ('informacion_instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.classrooms'),
        ),
        migrations.CreateModel(
            name='EventMemberDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.event')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.instructor')),
            ],
            options={
                'unique_together': {('evento', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.event')),
            ],
            options={
                'unique_together': {('event', 'colaborador')},
            },
        ),
    ]
