# Generated by Django 3.2.4 on 2023-04-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='class_code',
            new_name='codigo_clase',
        ),
        migrations.RenameField(
            model_name='classrooms',
            old_name='classroom_name',
            new_name='nombre_clase',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='section',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='seccion',
            field=models.CharField(default='Primer clase', max_length=100),
        ),
    ]
