# Generated by Django 3.2.4 on 2023-04-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_auto_20230405_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='codigo_clase',
            new_name='class_code',
        ),
        migrations.RenameField(
            model_name='classrooms',
            old_name='nombre_clase',
            new_name='classroom_name',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='seccion',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='section',
            field=models.CharField(default='Third Year', max_length=100),
        ),
    ]
